apiVersion: application-networking.k8s.aws/v1alpha1
kind: TargetGroupPolicy
metadata:
  name: prodcatalog-tgp
  namespace: prodcatalog-ns-lattice
spec:
  targetRef:
    group: ""
    kind: Service
    name: prodcatalog
    namespace: prodcatalog-ns-lattice
  protocol: HTTP
  protocolVersion: HTTP1
  healthCheck:
    enabled: true
    intervalSeconds: 10
    timeoutSeconds: 1
    healthyThresholdCount: 3
    unhealthyThresholdCount: 2
    path: "/"
    port: 5000
    protocol: HTTP
    protocolVersion: HTTP1
    statusMatch: "200"
