apiVersion: application-networking.k8s.aws/v1alpha1
kind: TargetGroupPolicy
metadata:
  name: proddetail-tgp-v1
  namespace: prodcatalog-ns-lattice
spec:
  targetRef:
    group: ""
    kind: Service
    name: proddetail
    namespace: prodcatalog-ns-lattice
  protocol: HTTP
  protocolVersion: HTTP1
  healthCheck:
    enabled: true
    intervalSeconds: 10
    timeoutSeconds: 1
    healthyThresholdCount: 3
    unhealthyThresholdCount: 2
    path: "/catalogDetail"
    port: 3000
    protocol: HTTP
    protocolVersion: HTTP1
    statusMatch: "200"
